apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      imagePullSecrets:
        - name: dockerhub-secret   # ðŸ‘ˆ REQUIRED
      containers:
        - name: ace
          image: moiz3388/ace13:latest
          ports:
            - containerPort: 7600
