apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: ace
          image: moiz3388/ace13:latest
          ports:
            - containerPort: 7600
          env:
            - name: LICENSE
              value: "accept"   # âœ… Required to prevent container from exiting
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

